competitions:
  - ID: 9
    name: ENGLAND_D1_LEAGUE
    teams: 20
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/first-division-bis-91-92-/ewigeTabelle/wettbewerb/EFD1
      - https://www.transfermarkt.es/premier-league/ewigeTabelle/wettbewerb/GB1

  - ID: 10
    name: ITALY_D1_LEAGUE
    teams: 20
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/serie-a/ewigeTabelle/wettbewerb/IT1

  - ID: 11
    name: SPAIN_D1_LEAGUE
    teams: 20
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/laliga/ewigeTabelle/wettbewerb/ES1

  - ID: 12
    name: FRANCE_D1_LEAGUE
    teams: 18
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/ligue-1/ewigeTabelle/wettbewerb/FR1

  - ID: 13
    name: NETHERLANDS_D1_LEAGUE
    teams: 18
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/eredivisie/ewigeTabelle/wettbewerb/NL1

  - ID: 14
    name: PORTUGAL_D1_LEAGUE
    teams: 18
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/liga-nos/ewigeTabelle/wettbewerb/PO1

  - ID: 39
    name: FAKE_PES_LEAGUE_EUROPE #BUNDESLIGA
    teams: 18
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/bundesliga/ewigeTabelle/wettbewerb/L1