competitions:
  - ID: 2
    name: UEFA_CHAMPIONS_LEAGUE
    primary: yes
    teams: 32
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/uefa-champions-league/ewigeTabelle/pokalwettbewerb/CL
      - https://www.transfermarkt.es/uefa-cup/ewigeTabelle/pokalwettbewerb/UEFA
      - https://www.transfermarkt.es/uefa-europa-conference-league/ewigeTabelle/pokalwettbewerb/UCOL

  - ID: 3
    name: UEFA_EUROPE_LEAGUE
    primary: no
    relegated_from: UEFA_CHAMPIONS_LEAGUE
    teams: 64
    ranking:
      type: all_time_table
      metric: points

  - ID: 5
    name: COPA_LIBERTADORES
    primary: yes
    teams: 21
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/copa-libertadores/ewigeTabelle/pokalwettbewerb/CLI
      - https://www.transfermarkt.es/copa-sudamericana/ewigeTabelle/pokalwettbewerb/CS
      - https://www.transfermarkt.es/copa-mercosur/ewigeTabelle/pokalwettbewerb/CMER
      - https://www.transfermarkt.es/copa-merconorte/ewigeTabelle/pokalwettbewerb/MERC
      - https://www.transfermarkt.es/copa-conmebol/ewigeTabelle/pokalwettbewerb/CCON

  - ID: 6
    name: COPA_SUDAMERICANA
    primary: no
    relegated_from: COPA_LIBERTADORES
    teams: 16
    ranking:
      type: all_time_table
      metric: points

  - ID: 8
    name: AFC_CHAMPIONS_LEAGUE
    primary: yes
    teams: 32
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/afc-champions-league-elite/ewigeTabelle/pokalwettbewerb/ACLE

  - ID: 9
    name: ENGLAND_D1_LEAGUE
    primary: yes
    teams: 20
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/first-division-bis-91-92-/ewigeTabelle/wettbewerb/EFD1
      - https://www.transfermarkt.es/premier-league/ewigeTabelle/wettbewerb/GB1

  - ID: 10
    name: ITALY_D1_LEAGUE
    primary: yes
    teams: 20
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/serie-a/ewigeTabelle/wettbewerb/IT1

  - ID: 11
    name: SPAIN_D1_LEAGUE
    primary: yes
    teams: 20
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/laliga/ewigeTabelle/wettbewerb/ES1

  - ID: 12
    name: FRANCE_D1_LEAGUE
    primary: yes
    teams: 18
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/ligue-1/ewigeTabelle/wettbewerb/FR1

  - ID: 13
    name: NETHERLANDS_D1_LEAGUE
    primary: yes
    teams: 18
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/eredivisie/ewigeTabelle/wettbewerb/NL1

  - ID: 14
    name: PORTUGAL_D1_LEAGUE
    primary: yes
    teams: 18
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/liga-nos/ewigeTabelle/wettbewerb/PO1

  - ID: 21
    name: BRAZIL_D1_LEAGUE
    primary: yes
    teams: 20
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/campeonato-brasileiro-serie-a/ewigeTabelle/wettbewerb/BRA1

  - ID: 22
    name: ARGENTINA_D1_LEAGUE
    primary: yes
    teams: 30
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/superliga/ewigeTabelle/wettbewerb/AR1N

  - ID: 23
    name: CHILE_D1_LEAGUE
    primary: yes
    teams: 16
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/primera-division-de-chile/ewigeTabelle/wettbewerb/CLPD

  - ID: 33
    name: EURO
    primary: yes
    teams: 24
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/europameisterschaft/ewigeTabelle/pokalwettbewerb/EURO

  - ID: 34
    name: COPA_AMERICA
    primary: yes
    teams: 12
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/copa-america/ewigeTabelle/pokalwettbewerb/COPA

  - ID: 35
    name: AFC_ASIA_CUP
    primary: yes
    teams: 24
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/afc-asian-cup/ewigeTabelle/pokalwettbewerb/AFAC

  - ID: 36
    name: AFRICA_NATIONS_CUP
    primary: yes
    teams: 24
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/afrika-cup/ewigeTabelle/pokalwettbewerb/AFCN

  - ID: 39
    name: FAKE_PES_LEAGUE_EUROPE #BUNDESLIGA
    primary: yes
    teams: 18
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/bundesliga/ewigeTabelle/wettbewerb/L1

  - ID: 50
    name: JAPAN_D1_LEAGUE
    primary: yes
    teams: 20
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/j1-league/ewigeTabelle/wettbewerb/JAP1

  - ID: 51
    name: JAPAN_D2_LEAGUE
    primary: no
    relegated_from: JAPAN_D1_LEAGUE
    teams: 20
    ranking:
      type: all_time_table
      metric: points

  - ID: 66
    name: ENGLAND_D2_LEAGUE
    primary: no
    relegated_from: ENGLAND_D1_LEAGUE
    teams: 24
    ranking:
      type: all_time_table
      metric: points

  - ID: 67
    name: SPAIN_D2_LEAGUE
    primary: no
    relegated_from: SPAIN_D1_LEAGUE
    teams: 22
    ranking:
      type: all_time_table
      metric: points

  - ID: 68
    name: FRANCE_D2_LEAGUE
    primary: no
    relegated_from: FRANCE_D1_LEAGUE
    teams: 18
    ranking:
      type: all_time_table
      metric: points

  - ID: 69
    name: ITALY_D2_LEAGUE
    primary: no
    relegated_from: ITALY_D1_LEAGUE
    teams: 20
    ranking:
      type: all_time_table
      metric: points

  - ID: 90
    name: BRAZIL_D2_LEAGUE
    primary: no
    relegated_from: BRAZIL_D1_LEAGUE
    teams: 20
    ranking:
      type: all_time_table
      metric: points

  - ID: 104
    name: MEXICO_D1_LEAGUE
    primary: yes
    teams: 18
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/liga-mx-clausura/ewigeTabelle/wettbewerb/MEX1
      - https://www.transfermarkt.es/liga-mx-apertura/ewigeTabelle/wettbewerb/MEXA

  - ID: 111
    name: BELGIUM_D1_LEAGUE
    primary: yes
    teams: 16
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/jupiler-pro-league/ewigeTabelle/wettbewerb/BE1

  - ID: 114
    name: RUSSIA_D1_LEAGUE
    primary: yes
    teams: 16
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/premier-liga/ewigeTabelle/wettbewerb/RU1

  - ID: 117
    name: SWITZERLAND_D1_LEAGUE
    primary: yes
    teams: 12
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/super-league/ewigeTabelle/wettbewerb/C1

  - ID: 119
    name: TURKEY_D1_LEAGUE
    primary: yes
    teams: 18
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/super-lig/ewigeTabelle/wettbewerb/TR1

  - ID: 122
    name: COLOMBIA_D1_LEAGUE
    primary: yes
    teams: 20
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/liga-dimayor-i/ewigeTabelle/wettbewerb/COLP
      - https://www.transfermarkt.es/liga-dimayor-ii/ewigeTabelle/wettbewerb/COL1

  - ID: 125
    name: CHINA_D1_LEAGUE
    primary: yes
    teams: 16
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/chinese-super-league/ewigeTabelle/wettbewerb/CSL

  - ID: 128
    name: DENMARK_D1_LEAGUE
    primary: yes
    teams: 12
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/superligaen/ewigeTabelle/wettbewerb/DK1

  - ID: 137
    name: SCOTLAND_D1_LEAGUE
    primary: yes
    teams: 12
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/scottish-premiership/ewigeTabelle/wettbewerb/SC1

  - ID: 139
    name: THAILAND_D1_LEAGUE
    primary: yes
    teams: 16
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/thai-league/ewigeTabelle/wettbewerb/THA1

  - ID: 147
    name: USA_D1_LEAGUE
    primary: yes
    teams: 30
    ranking:
      type: all_time_table
      metric: points
    sources:
      - https://www.transfermarkt.es/major-league-soccer/ewigeTabelle/wettbewerb/MLS1