teams:
  - ID_pes: 100
    name: Manchester United F.C.
    source_coach:
      - https://www.transfermarkt.es/manchester-united/mitarbeiterhistorie/verein/985

  - ID_pes: 101
    name: Arsenal F.C.
    source_coach:
      - https://www.transfermarkt.es/fc-arsenal/mitarbeiterhistorie/verein/11

  - ID_pes: 102
    name: Chelsea F.C.
    source_coach:
      - https://www.transfermarkt.es/fc-chelsea/mitarbeiterhistorie/verein/631